# Generated by Django 4.2.5 on 2023-11-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='like',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
